#!/usr/bin/env ruby 

require_relative './lib/input_parser'
require_relative './lib/hotel_helper'
require_relative './lib/seeds/hotels'
require_relative './lib/seeds/customer_types'

ARGF.each do |line|
  begin
    print line
    input = InputParser.parse(line)
    p HotelHelper.find_cheapest_hotel(input[:customer_type],
                                            input[:days]).name
  rescue ArgumentError => e
    p e.backtrace
  end
end
