#!/usr/bin/env ruby 

require_relative './lib/input_parser'
require_relative './lib/hotel_helper'
require_relative './lib/seeds/hotels'
require_relative './lib/seeds/customer_types'

ARGF.each do |line|
  next if line.strip.empty?

  begin
    input = InputParser.parse(line)
    cheapest = HotelHelper.find_cheapest_hotel(input[:customer_type],
                                            input[:dates])
    puts line
    puts "Cheapest hotel: #{ cheapest.name }"
    puts
  rescue ArgumentError => e
    puts e.backtrace
  end
end
